accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [

    # create같은 경우는 특정 View 상속 받아서, 파라미터 설정하고 그랬었는데
    #login,logout은 거창한 것이 필요 없어서 이런식으로 간단하게 해도 된다.
    #login은 템플릿을 지정해 주어야 한다. (로그인 할 때 보는 화면)
    path("login/", LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),

    #class based view에서는 .as_view()를 붙어야 한다.
    path("create/", AccountCreateView.as_view(), name='create'),
    path("update/<int:pk>", AccountUpdateView.as_view(), name='update'),

    #특정유저의 정보를 받으려고 한다. => 고유번호를 받아야 한다
    #detail/<int:pk>  pk라는 이름의 int정보를 받겠다
    path("detail/<int:pk>", AccountDetailView.as_view(), name='detail'),
    path("delete/<int:pk>", AccountDeleteView.as_view(), name='delete'),

]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    #SET_NULL : 나중에 유저가 사라지면, 알수 없음 정도로 표시
    writer=models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=200,null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True #초기화 이후에 id칸을 비활성화

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
# Create your views here.
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm

from articleapp.models import Article
has_ownership = [account_ownership_required, login_required]



class AccountCreateView(CreateView):  # CreateView를 상속받음
    model = User  # 어떤 모델을 사용할 것이다. #User - 장고에서 기본 제공해주는 모델
    form_class = UserCreationForm  # User 모델을 만들기 위해 사용할 form이 필요하다 #UserCreationForm - 장고가 기본 form을 제공해준다.
    success_url = reverse_lazy('home')  # 계정을 만드는데 성공했다면, 어느 경로로 다시 재연결 할 것인가
    # reverse_lazy(경로)는 reverse()와 기능은 같은데 class에서 사용하는 방식이다.
    template_name = "accountapp/create.html"  # 템플릿을 지정해주어야 한다. (회원가입을 할 때 보는 화면)
    # create.html을 새로 생성하면 당연히 urls.py에도 연결을 해주어야 한다.


# CreateView는 뭔가 만들어야 하니까 form이나 성공했을때 경로 등 정해줘야 하지만, DetailView(reading)은 더 간단하다
class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User  # 어떤 모델을 사용할 것인지
    context_object_name = "target_user" #특정 pk유저 정보를 확인하면 그 유저를 보여줘야 한다.
                                        #연예인 인스타 들어갔는데 내 정보가 뜨는게 아니라 그 연예인 정보가 떠야함
    template_name = 'accountapp/detail.html'  # 어떻게 시각화할 것인지

    paginate_by = 25

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = "target_user"
    form_class = AccountUpdateForm
    success_url = reverse_lazy('home')
    template_name = "accountapp/update.html"

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = "target_user"
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
<!--'base.html'을 extends 했으므로 header,footer는 바뀌지 않고 content부분만 바뀐다-->
{% extends 'base.html'%}
<!--부트스트랩 쓰려면 다운 받아서 settings.py의 INSTALLED_APPS에 추가해준다. 사용할 페이지에는 아래와 같이 적는다.-->
{% load bootstrap4 %}

{% block content %}

    <div style="text-align:center;max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>SignUp</h4>
        </div>
<!--        action에는 요청을 보내는 url이 들어간다. veiws.py에서 reverse(경로)로 쓰던 것처럼 HTML은 아래와 같이 쓴다.
            accountapp라는 앱에서 create라는 routing으로 가라-->
        <form action="{% url 'accountapp:create'%}" method="post">
<!--        POST방식을 쓰기 위해서는 csrf토큰이 필요하다-->
            {% csrf_token %}

<!--        views.py의 AccountCreateView에서 form_class로 form을 받아왔다. 그걸 그대로 쓰면 된다.-->
            <!--{{ form }}-->

<!--        form의 형태를 더 예쁘게 하기 위해 bootstrap이 적용된 form을 사용한다.-->
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
<!--            버튼을 알약 형태로, col은 너비(12가 100%-부모의 너비를 모두 가져가는 것) mt는 margin-top-->
        </form>
    </div>


{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html'%}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align:center;max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Quit</h4>
        </div>
<!--        action에는 요청을 보내는 url이 들어간다. veiws.py에서 reverse(경로)로 쓰던 것처럼 HTML은 아래와 같이 쓴다.
            accountapp라는 앱에서 delete라는 routing으로 가라-->
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>


{% endblock %}

accountapp/templates/accountapp/detail.html
<!--'base.html'을 extends 했으므로 header,footer는 바뀌지 않고 content부분만 바뀐다-->
{% extends 'base.html' %}


{% block content %}

  <div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">

      {% if target_user.profile %}
      <img src="{{ target_user.profile.image.url }}" alt=""
           style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem; object-fit: cover;">
      <h2 style="font-family: 'NanumSquareB'">
        {{ target_user.profile.nickname }}
          {% if target_user == user %}
            <a class="material-icons"
             style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;"
             href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
              edit
          </a>
          {% endif %}
      </h2>
      <h5 style="margin-bottom:3rem;">
        {{ target_user.profile.message }}
      </h5>
      {% else %}
        {% if target_user == user %}
        <a href="{% url 'profileapp:create' %}">
          <h2 style="font-family: 'NanumSquareB'">
            Create Profile
          </h2>
        </a>
        {% else %}
        <h2>
          닉네임 미설정
        </h2>
        {% endif %}
      {% endif %}

      {% if target_user == user %}
       <a class="material-icons"
           style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;"
           href="{% url 'accountapp:update' pk=user.pk %}">
            settings
        </a>
        <a class="material-icons"
           style="box-shadow: 0 0 4px #fcc; border-radius: 10rem; padding: .4rem;"
           href="{% url 'accountapp:delete' pk=user.pk %}">
            cancel
        </a>
      {% endif %}

    </div>

    <div>

      {% include 'snippets/list_fragment.html' with article_list=object_list %}

    </div>
  </div>

{% endblock %}

accountapp/templates/accountapp/login.html
<!--'base.html'을 extends 했으므로 header,footer는 바뀌지 않고 content부분만 바뀐다-->
{% extends 'base.html'%}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div>
            <h4>Login</h4>
        </div>
        <div>
<!--            action에 아무것도 없으면, 지금 페이지 주소 그대로 다시 요청을 보낸다는 뜻
                {% url 'accountapp:login' %} 이렇게 썼어도 정상적으로 작동한다.-->
            <form action="" method="post">
                {% csrf_token %}
<!--                {{ form }}-->
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
            </form>
        </div>
    </div>


{% endblock %}

accountapp/templates/accountapp/update.html
<!--'base.html'을 extends 했으므로 header,footer는 바뀌지 않고 content부분만 바뀐다-->
{% extends 'base.html'%}
<!--부트스트랩 쓰려면 다운 받아서 settings.py의 INSTALLED_APPS에 추가해준다. 사용할 페이지에는 아래와 같이 적는다.-->
{% load bootstrap4 %}

{% block content %}

    <div style="text-align:center;max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Change Info</h4>
        </div>
<!--        action에는 요청을 보내는 url이 들어간다. veiws.py에서 reverse(경로)로 쓰던 것처럼 HTML은 아래와 같이 쓴다.
            accountapp라는 앱에서 update라는 routing으로 가라-->
        <form action="{% url 'accountapp:update' pk=target_user.pk%}" method="post">
<!--        POST방식을 쓰기 위해서는 csrf토큰이 필요하다-->
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}