accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [

    # create같은 경우는 특정 View 상속 받아서, 파라미터 설정하고 그랬었는데
    #login,logout은 거창한 것이 필요 없어서 이런식으로 간단하게 해도 된다.
    #login은 템플릿을 지정해 주어야 한다. (로그인 할 때 보는 화면)
    path("login/", LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),

    #class based view에서는 .as_view()를 붙어야 한다.
    path("create/", AccountCreateView.as_view(), name='create'),
    path("update/<int:pk>", AccountUpdateView.as_view(), name='update'),

    #특정유저의 정보를 받으려고 한다. => 고유번호를 받아야 한다
    #detail/<int:pk>  pk라는 이름의 int정보를 받겠다
    path("detail/<int:pk>", AccountDetailView.as_view(), name='detail'),
    path("delete/<int:pk>", AccountDeleteView.as_view(), name='delete'),

]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectListView, ProjectCreateView, ProjectDetailView

app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),

    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'NanumSquare';">

    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div class="pragmatic_footer">

    <div class="pragmatic_footer_button">
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스 소개</span>
    </div>

    <div style="margin-top:1rem;">
        <h6 class="pragmatic_logo">pragmatic</h6>
    </div>


</div>

templates/head.html
<!--static 파일(base.css)을 사용하기 위함-->
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PRAGMATIC</title>
    <!--  BOOTSTRAP LINK  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!--  google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

     <!--  GOOGLE MATERIAL ICONS  -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">


    <!--  DEFAULT CSS LINK  -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <!--  Naver font  -->
    <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square.css" rel="stylesheet">
</head>

templates/header.html
<!--margin: 2rem 0  상하 2rem, 좌우 0-->
<div class="pragmatic_header">
    <div>
        <h1 class="pragmatic_logo">Pragmatic</h1>
    </div>
    <div class="pragmatic_header_navbar">
            <a href="{% url 'articleapp:list' %}" class="prgmatic_header_nav">
            <span>Articles</span>
        </a>

         <a href="{% url 'projectapp:list' %}" class="prgmatic_header_nav">
                <span>Projects</span>
            </a>

        <a href="{% url 'subscribeapp:list' %}" class="prgmatic_header_nav">
                <span>Subscription</span>
            </a>


<!--    로그인 :user가 아니면 =>login으로/ user이면 logout으로-->
<!--    login하고 나서 그다음에 연결되어야 하는 경로를 next로 적어준다.
        next={{request.path}}가 없으면 accounts/profile이라는 페이지로 넘어가더라
        next 값을 사용할때 {{ request.path }} 를 사용하는 건, 홈페이지 상단의 login 버튼을 눌렀을때,
        그 버튼을 누를때 보고 있던 페이지의 정보를 넘겨주기 위함입니다. 해당 페이지의 정보를 넘겨줌으로써,
        로그인 이후 로그인 버튼을 누른 페이지로 다시 되돌아갈 수 있도록 연결해주는 역할을 합니다. -->
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="prgmatic_header_nav">
            <span>login</span>
        </a>
        <a href="{% url 'accountapp:create' %}" class="prgmatic_header_nav">
            <span>SignUp</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}" class="prgmatic_header_nav">
            <span>MyPage</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="prgmatic_header_nav">
            <span>logout</span>
        </a>
        {% endif %}

    </div>

</div>